### ISSUE TITLE
Some question about this outstanding work

### ISSUE THREAD

**Issue by DylanWangWQF** [ut-osa/telekine#1]
HI @zhipeng-jia ,
  Sry for my noise, I have some questions about this work.
  1. According to your paper, you test it on an Intel server with  AMD GPU, (i.e., Intel CPU processor + AMD GPU), right? And you didn't consider CPU TEE (e.g., Intel SGX / AMD SEV)?
  2. I noticed that you run this prototype with AMD ROCm 1.8 while the current version is 4.3 or higher else. Are you still maintaining this work elsewhere?

**Comment by zhipeng-jia** [comment]
For (1): Yes, we do not consider CPU TEEs in our prototype implementation and experiments.

For (2): Telekine is not maintained for a newer ROCm version.

**Comment by DylanWangWQF** [comment]
@zhipeng-jia 
Many thanks for your reply!
In the paper, it points out the components can be CPU TEE and GPU TEE. 
Though this implementation does not consider CPU TEE, it could be Intel SGX+GPU TEE (**Lib Teleking** deployed in SGX)?

**Comment by zhipeng-jia** [comment]
LibTelekine does not require a CPU TEE, because it's running on the client side (trusted).

The paper includes a paragraph about this point:
![image](https://user-images.githubusercontent.com/6553274/136710550-f7a1876d-71eb-4917-83d4-03de34525aa6.png)

**Comment by DylanWangWQF** [comment]
Got it! Thanks!
